//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        public int Id { get; set; }
        public string security_id { get; set; }
        public string name { get; set; }
        public System.DateTime birthdate { get; set; }
        public System.DateTime add_date { get; set; }
        public Nullable<System.DateTime> upd_date { get; set; }
    }
}
